"""Generate the SLOBAC taxonomy index table from per-entry canonical headers.

The slug / severity / detection-scope index is consumed in two places in the
manifesto bundle:

* ``skills/slobac-audit/SKILL.md`` — read by the audit orchestrator at runtime
  to partition in-scope smells between the batch and cross-suite assessors,
  without fanning out to all 15 canonical entries.
* ``skills/slobac-audit/references/docs/taxonomy/README.md`` — human-readable
  navigation index for the manifesto site.

Both copies are generated by this module from the single source of truth: the
header table at the top of every ``skills/slobac-audit/references/docs/taxonomy/<slug>.md``.
The hand-curated content elsewhere on each target page (prose, links,
footnotes) is preserved by sentinel-bracketed replacement.

This module is intentionally stdlib-only.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Literal, Sequence


SEVERITY_ORDER: dict[str, int] = {
    "Critical": 0,
    "High": 1,
    "Medium": 2,
    "Low": 3,
}

VALID_SCOPES: frozenset[str] = frozenset({"per-test", "per-file", "cross-suite"})

# Per CONTRIBUTING.md, every taxonomy entry's first content after the H1 is
# a 4-column markdown table whose data row carries `Slug | Severity |
# Detection Scope | Protects`. The header (line 3 by convention) and
# separator (line 4) are skipped; we match the data row anywhere in the
# file so authors retain freedom to add front-matter or blank lines above.
_HEADER_DATA_ROW = re.compile(
    r"^\|\s*`(?P<slug>[a-z][a-z0-9-]*)`\s*"
    r"\|\s*(?P<severity>[A-Za-z]+)\s*"
    r"\|\s*(?P<scope>[a-z, -]+?)\s*"
    r"\|\s*(?P<protects>.+?)\s*\|\s*$",
    re.MULTILINE,
)

LinkTarget = Literal["readme", "skill"]


@dataclass(frozen=True)
class TaxonomyEntry:
    """Parsed canonical-header row from a single taxonomy entry markdown file.

    Attributes
    ----------
    slug:
        The canonical slug (filename minus ``.md``), without backticks.
    severity:
        One of ``Critical``, ``High``, ``Medium``, ``Low``.
    scopes:
        Tuple of detection scopes in the original declaration order; preserved
        so multi-scope entries (e.g. ``deliverable-fossils`` =
        ``per-test, cross-suite``) round-trip byte-for-byte.
    """

    slug: str
    severity: str
    scopes: tuple[str, ...]


class TaxonomyIndexError(ValueError):
    """Structured error for taxonomy-index generator failures.

    Carries the offending file path and the field name (``severity``,
    ``scope``, ``header``, ``marker``, ...) so CI logs and contributor errors
    point directly at the broken thing.
    """

    def __init__(self, message: str, *, file_path: Path | None = None, field: str | None = None) -> None:
        super().__init__(message)
        self.file_path = file_path
        self.field = field


def parse_entry(path: Path) -> TaxonomyEntry:
    """Parse a single canonical taxonomy entry's header table.

    Reads the file at ``path`` and returns the
    ``(slug, severity, scopes)`` triple from the header table at the top of
    the file (line 5 by convention; see ``CONTRIBUTING.md``).

    Raises
    ------
    TaxonomyIndexError
        If the header table is missing, malformed, or carries values outside
        the documented enums.
    """
    text = path.read_text(encoding="utf-8")
    match = _HEADER_DATA_ROW.search(text)
    if match is None:
        raise TaxonomyIndexError(
            f"no canonical header data row found in {path}",
            file_path=path,
            field="header",
        )

    slug = match.group("slug")
    severity = match.group("severity")
    scope_raw = match.group("scope")

    if severity not in SEVERITY_ORDER:
        raise TaxonomyIndexError(
            f"{path}: severity {severity!r} not in "
            f"{sorted(SEVERITY_ORDER)}",
            file_path=path,
            field="severity",
        )

    scopes = tuple(s.strip() for s in scope_raw.split(","))
    for scope in scopes:
        if scope not in VALID_SCOPES:
            raise TaxonomyIndexError(
                f"{path}: detection scope {scope!r} not in "
                f"{sorted(VALID_SCOPES)}",
                file_path=path,
                field="scope",
            )

    return TaxonomyEntry(slug=slug, severity=severity, scopes=scopes)


def order_entries(entries: Iterable[TaxonomyEntry]) -> list[TaxonomyEntry]:
    """Return entries sorted by severity descending, slug ascending.

    Severity ordering: ``Critical → High → Medium → Low`` (see
    :data:`SEVERITY_ORDER`).
    """
    return sorted(entries, key=lambda e: (SEVERITY_ORDER[e.severity], e.slug))


def render_table(entries: Sequence[TaxonomyEntry], *, link_target: LinkTarget) -> str:
    """Render the index as a 3-column markdown table.

    Columns: ``Slug | Severity | Detection Scope``. The slug column links to
    the canonical entry; the relative target depends on ``link_target``:

    * ``"readme"`` — used when the table lands inside
      ``taxonomy/README.md``; links are ``./<slug>.md``.
    * ``"skill"`` — used when the table lands inside
      ``skills/slobac-audit/SKILL.md``; links are
      ``references/docs/taxonomy/<slug>.md``.

    Multi-scope entries are rendered with the original comma-joined scope
    string, byte-for-byte.
    """
    lines = [
        "| Slug | Severity | Detection Scope |",
        "|---|---|---|",
    ]
    for entry in entries:
        if link_target == "readme":
            link = f"./{entry.slug}.md"
        else:
            link = f"references/docs/taxonomy/{entry.slug}.md"
        slug_cell = f"[`{entry.slug}`]({link})"
        scope_cell = ", ".join(entry.scopes)
        lines.append(f"| {slug_cell} | {entry.severity} | {scope_cell} |")
    return "\n".join(lines) + "\n"


def replace_between_sentinels(
    text: str,
    content: str,
    *,
    marker_id: str = "taxonomy-index",
) -> str:
    """Replace the region between sentinel HTML comments with ``content``.

    The sentinels are
    ``<!-- BEGIN: <marker_id> -->`` and ``<!-- END: <marker_id> -->``.
    Surrounding bytes (including the sentinel lines themselves) are
    unchanged. ``content`` is inserted with one ``\\n`` separator before and
    after, normalised so re-runs are byte-identical.

    Raises
    ------
    TaxonomyIndexError
        If either marker is missing or appears more than once.
    """
    begin = f"<!-- BEGIN: {marker_id} -->"
    end = f"<!-- END: {marker_id} -->"

    begin_count = text.count(begin)
    end_count = text.count(end)
    if begin_count == 0:
        raise TaxonomyIndexError(
            f"missing sentinel: {begin}", field="marker"
        )
    if end_count == 0:
        raise TaxonomyIndexError(
            f"missing sentinel: {end}", field="marker"
        )
    if begin_count > 1 or end_count > 1:
        raise TaxonomyIndexError(
            f"sentinel {marker_id!r} appears more than once "
            f"(BEGIN={begin_count}, END={end_count})",
            field="marker",
        )

    begin_idx = text.index(begin)
    try:
        end_idx = text.index(end, begin_idx + len(begin))
    except ValueError:
        raise TaxonomyIndexError(
            f"sentinel END appears before BEGIN for marker {marker_id!r}",
            field="marker",
        )

    body = content if content.endswith("\n") else content + "\n"
    return (
        text[: begin_idx + len(begin)]
        + "\n"
        + body
        + text[end_idx:]
    )


def regenerate(
    taxonomy_dir: Path,
    targets: Sequence[tuple[Path, LinkTarget]],
) -> None:
    """End-to-end regeneration: parse, order, render, write each target.

    Globs ``taxonomy_dir/*.md`` excluding ``README.md``, parses every
    enumerated file (raising on the first malformed entry), orders by the
    documented sort key, renders per ``link_target``, and writes each target
    in place via :func:`replace_between_sentinels`.

    The function is idempotent: a second invocation against the same inputs
    produces zero file diff.

    Raises
    ------
    TaxonomyIndexError
        If no taxonomy entries are found (broken repository state), or if any
        entry file is malformed.
    """
    entries = []
    for path in sorted(taxonomy_dir.glob("*.md")):
        if path.name == "README.md":
            continue
        entries.append(parse_entry(path))

    if not entries:
        raise TaxonomyIndexError(
            f"no taxonomy entries found in {taxonomy_dir} — "
            "at least one non-README.md entry is required",
            file_path=taxonomy_dir,
            field="header",
        )

    ordered = order_entries(entries)

    for target_path, link_target in targets:
        original = target_path.read_text(encoding="utf-8")
        rendered = render_table(ordered, link_target=link_target)
        updated = replace_between_sentinels(original, rendered)
        if updated != original:
            target_path.write_text(updated, encoding="utf-8")
